server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-usuarios
          uri: ${URL_USUARIOS}
          predicates:
            - Path=/api/usuarios/**

        - id: servicio-suscripciones
          uri: ${URL_SUSCRIPCIONES}
          predicates:
            - Path=/api/suscripciones/**