server:
  port: 8089
spring:
  application:
    name: servicio-suscripciones
  datasource:
    url: jdbc:h2:mem:suscripcionesdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update